DROP TABLE IF EXISTS `monitor_alert_record`;
CREATE TABLE `monitor_alert_record` (
 `id` bigint NOT NULL AUTO_INCREMENT COMMENT '告警记录-ID',
 `alert_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '告警名称',
 `alert_start_time` datetime NOT NULL COMMENT '告警开始时间',
 `alert_end_time` datetime DEFAULT NULL COMMENT '告警结束时间',
 `alert_source` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '告警来源',
 `env` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '环境信息',
 `monitor_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '告警类型',
 `status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '告警状态',
 `namespace` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '命名空间',
 `pod` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'pod',
 `instance` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'instance',
 `vhost` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'vhost',
 `queue` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'queue',
 `node` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'node',
 `url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'url',
 `abi_origin_prometheus` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'abi_origin_prometheus',
 `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'name',
 `team` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '团队',
 `summary` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'summary',
 `description` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'description',
 `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
 `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
 `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
 `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
 `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
 `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
 PRIMARY KEY (`id`) USING BTREE,
 INDEX `idx_alert_name` (`alert_name`) USING BTREE,
 INDEX `idx_alert_start_time` (`alert_start_time`) USING BTREE,
 INDEX `idx_alert_end_time` (`alert_end_time`) USING BTREE,
 INDEX `idx_monitor_type` (`monitor_type`) USING BTREE,
 INDEX `idx_status` (`status`) USING BTREE,
 INDEX `idx_namespace` (`namespace`) USING BTREE,
 INDEX `idx_pod` (`pod`) USING BTREE,
 INDEX `idx_instance` (`instance`) USING BTREE,
 INDEX `idx_vhost` (`vhost`) USING BTREE,
 INDEX `idx_queue` (`queue`) USING BTREE,
 INDEX `idx_node` (`node`) USING BTREE,
 INDEX `idx_url` (`url`) USING BTREE,
 INDEX `idx_abi_origin_prometheus` (`abi_origin_prometheus`) USING BTREE
) ENGINE=InnoDB CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='告警记录表';
